import test from 'node:test';import assert from 'node:assert/strict';
import { BleAdapter, BleDevice, UUID } from '../miniprogram/core/ble/ble-adapter';import { BleAdapterState, BleCharacteristic, BleDisconnectEvent } from '../miniprogram/core/ble/ble-types';import { BleConnectionManager } from '../miniprogram/core/ble/ble-connection-manager';import { BleWriteQueue } from '../miniprogram/core/ble/ble-write-queue';import { BleCommandClient } from '../miniprogram/core/ble/ble-command-client';import { decodeCommandRequest, decodeFrame, encodeCommandResponse, encodeFrame } from '../miniprogram/core/protocol/ble-codec';import { DeviceStore } from '../miniprogram/core/store/device-store';

class MockAdapter implements BleAdapter {openError?:Error;services=[UUID.service];characteristics:BleCharacteristic[]=[{uuid:UUID.notify,properties:{notify:true}},{uuid:UUID.write,properties:{write:true}}];devices:BleDevice[]=[];writes:Uint8Array[]=[];writeActive=0;maxWriteActive=0;found?: (d:BleDevice)=>void;notification?: (d:Uint8Array)=>void;adapterListeners=new Set<(s:BleAdapterState)=>void>();connectionListeners=new Set<(e:BleDisconnectEvent)=>void>();opened=0;stopped=0;disposed=false;
 async open(){this.opened++;if(this.openError)throw this.openError}async close(){}async startDiscovery(f:(d:BleDevice)=>void){this.found=f;this.devices.forEach(f)}async stopDiscovery(){this.stopped++}async connect(){}async disconnect(){}async discoverServices(){return this.services}async discoverCharacteristics(){return this.characteristics}async subscribe(_d:string,_s:string,_c:string,f:(d:Uint8Array)=>void){this.notification=f}async write(_d:string,_s:string,_c:string,data:Uint8Array){this.writeActive++;this.maxWriteActive=Math.max(this.maxWriteActive,this.writeActive);await Promise.resolve();this.writes.push(data);this.writeActive--}onAdapterStateChange(f:(s:BleAdapterState)=>void){this.adapterListeners.add(f);return()=>this.adapterListeners.delete(f)}onConnectionStateChange(f:(e:BleDisconnectEvent)=>void){this.connectionListeners.add(f);return()=>this.connectionListeners.delete(f)}dispose(){this.disposed=true}}
const device={deviceId:'opaque-ios-id',name:'W02_TEST',RSSI:-55};
test('adapter open failure becomes unavailable',async()=>{const a=new MockAdapter();a.openError=new Error('permission denied');const m=new BleConnectionManager(a);await m.initialize();assert.equal(m.state,'ADAPTER_UNAVAILABLE')});
test('scan deduplicates and refreshes RSSI',async()=>{const a=new MockAdapter(),m=new BleConnectionManager(a);await m.initialize();await m.scan(1000);a.found?.({...device,RSSI:-70});a.found?.({...device,RSSI:-42});assert.equal(m.devices.length,1);assert.equal(m.devices[0].RSSI,-42);await m.stopScan();assert.equal(m.state,'CLOSED')});
test('normal connection discovers FFE0 FFE1 FFE2',async()=>{const a=new MockAdapter();const states:string[]=[];const m=new BleConnectionManager(a,{onState:s=>states.push(s)});await m.initialize();await m.connect(device);assert.equal(m.state,'READY');assert.deepEqual(states.slice(-5),['CONNECTING','DISCOVERING','SUBSCRIBING','VERIFYING','READY'])});
test('missing service is incompatible',async()=>{const a=new MockAdapter();a.services=[];const m=new BleConnectionManager(a);await m.initialize();await m.connect(device);assert.equal(m.state,'INCOMPATIBLE')});
test('missing notify characteristic is incompatible',async()=>{const a=new MockAdapter();a.characteristics=[{uuid:UUID.write,properties:{write:true}}];const m=new BleConnectionManager(a);await m.initialize();await m.connect(device);assert.equal(m.state,'INCOMPATIBLE')});
test('unexpected disconnect and intentional disconnect differ',async()=>{const a=new MockAdapter(),m=new BleConnectionManager(a);await m.initialize();await m.connect(device);a.connectionListeners.forEach(f=>f({deviceId:device.deviceId,connected:false}));assert.equal(m.state,'RECONNECT_WAIT');await m.disconnect();assert.equal(m.state,'CLOSED')});
test('old notification callback is isolated by generation',async()=>{const a=new MockAdapter();let frames=0;const m=new BleConnectionManager(a,{onFrame:()=>frames++});await m.initialize();await m.connect(device);const old=a.notification!;await m.disconnect();old(encodeFrame(3,1,1,new Uint8Array(8)));assert.equal(frames,0)});
test('write queue chunks at 20 bytes and serializes',async()=>{const a=new MockAdapter(),q=new BleWriteQueue(a,'d','s','c',true,20);await Promise.all([q.write(new Uint8Array(45)),q.write(new Uint8Array(3))]);assert.deepEqual(a.writes.map(x=>x.length),[20,20,5,3]);assert.equal(a.maxWriteActive,1)});
test('command client rejects mutating operations',async()=>{const a=new MockAdapter(),c=new BleCommandClient(new BleWriteQueue(a,'d','s','c'));await assert.rejects(c.request(0x10),/not allowed/)});
test('command response must match transaction and operation',async()=>{const a=new MockAdapter(),c=new BleCommandClient(new BleWriteQueue(a,'d','s','c'),100);const promise=c.request(1);await new Promise(r=>setTimeout(r,0));const request=decodeCommandRequest(decodeFrame(Uint8Array.from(a.writes.flatMap(x=>[...x]))).payload);c.onFrame(decodeFrame(encodeCommandResponse({transactionId:request.transactionId,operation:2,result:0,detailCode:0,data:new Uint8Array(12)})));assert.equal(c.metrics.mismatches,1);c.onFrame(decodeFrame(encodeCommandResponse({transactionId:request.transactionId,operation:1,result:0,detailCode:0,data:new Uint8Array(12)})));assert.equal((await promise).operation,1)});
test('read-only retry preserves identical bytes and transaction id',async()=>{const a=new MockAdapter(),c=new BleCommandClient(new BleWriteQueue(a,'d','s','c'),5);const promise=c.request(2);await new Promise(r=>setTimeout(r,8));assert.ok(a.writes.length>=2);const first=Buffer.from(a.writes[0]).toString('hex'),second=Buffer.from(a.writes[1]).toString('hex');assert.equal(first,second);await assert.rejects(promise,/timeout/)});
test('store applies telemetry and exposes stale policy',()=>{const s=new DeviceStore();const payload=new Uint8Array(42);payload[36]=1;s.applyFrame(decodeFrame(encodeFrame(1,1,1,payload)),Date.now()-1500);assert.equal(s.weight?.stable,true);assert.equal(s.fastStale,true);assert.equal(s.fastInvalid,false);s.applyFrame(decodeFrame(encodeFrame(1,2,2,payload)));assert.equal(s.fastStale,false)});
test('gap diagnostics do not clear last valid weight',()=>{const s=new DeviceStore();const payload=new Uint8Array(42);s.applyFrame(decodeFrame(encodeFrame(1,1,1,payload)));s.syncParser({crcErrors:0,resyncBytes:4,sequenceGaps:1,duplicates:0});assert.ok(s.weight);assert.equal(s.diagnostics.sequenceGaps,1);assert.equal(s.diagnostics.resyncBytes,4)});
test('diagnostic events are bounded',()=>{const s=new DeviceStore();for(let i=0;i<30;i++)s.recordError(`error-${i}`);assert.equal(s.diagnosticEvents().length,20)});
