#ifndef COMMAND_TYPES_H
#define COMMAND_TYPES_H

#include <stdint.h>

typedef enum
{
    COMMAND_SOURCE_LOCAL_KEY = 0,
    COMMAND_SOURCE_MODBUS,
    COMMAND_SOURCE_BLE,
    COMMAND_SOURCE_USB,
    COMMAND_SOURCE_DIAGNOSTIC
} CommandSource;

typedef enum
{
    COMMAND_GET_WEIGHT = 0,
    COMMAND_ZERO,
    COMMAND_RESET_ZERO,
    COMMAND_TARE,
    COMMAND_CLEAR_TARE,
    COMMAND_GET_CONFIG,
    COMMAND_BEGIN_CONFIG_EDIT,
    COMMAND_SET_CONFIG_FIELD,
    COMMAND_COMMIT_CONFIG_EDIT,
    COMMAND_CANCEL_CONFIG_EDIT,
    COMMAND_REQUEST_CONFIG_SAVE,
    COMMAND_CALIBRATION_BEGIN,
    COMMAND_CALIBRATION_CAPTURE_ZERO,
    COMMAND_CALIBRATION_SET_SPAN_WEIGHT,
    COMMAND_CALIBRATION_CAPTURE_SPAN,
    COMMAND_CALIBRATION_COMMIT,
    COMMAND_CALIBRATION_CANCEL,
    COMMAND_SET_WEIGHT_VIEW,
    COMMAND_REQUEST_MANUAL_OUTPUT,
    COMMAND_FACTORY_RESET_REQUEST,
    COMMAND_FACTORY_RESET_CONFIRM,
    COMMAND_FACTORY_RESET_CANCEL,
    COMMAND_COUNT
} CommandId;

typedef enum
{
    COMMAND_RESULT_OK = 0,
    COMMAND_RESULT_ACCEPTED,
    COMMAND_RESULT_NOT_IMPLEMENTED,
    COMMAND_RESULT_INVALID_ARGUMENT,
    COMMAND_RESULT_INVALID_STATE,
    COMMAND_RESULT_NOT_STABLE,
    COMMAND_RESULT_NOT_CALIBRATED,
    COMMAND_RESULT_OUT_OF_ZERO_RANGE,
    COMMAND_RESULT_OVERLOAD,
    COMMAND_RESULT_BUSY,
    COMMAND_RESULT_STORAGE_UNAVAILABLE,
    COMMAND_RESULT_POWER_UNSAFE,
    COMMAND_RESULT_INTERNAL_ERROR
} CommandResult;

typedef struct
{
    CommandId id;
    CommandSource source;
    int32_t value0;
    int32_t value1;
    uint32_t flags;
} CommandRequest;

typedef struct
{
    CommandResult result;
    int32_t value0;
    int32_t value1;
    uint32_t status_flags;
} CommandResponse;

#endif /* COMMAND_TYPES_H */
