#ifndef METROLOGY_CONFIG_VALIDATOR_H
#define METROLOGY_CONFIG_VALIDATOR_H

#include "device_config.h"

typedef enum
{
    METROLOGY_CONFIG_OK = 0,
    METROLOGY_CONFIG_NULL,
    METROLOGY_CONFIG_INVALID_CAPACITY,
    METROLOGY_CONFIG_INVALID_DIVISION,
    METROLOGY_CONFIG_INVALID_DECIMALS,
    METROLOGY_CONFIG_INVALID_FILTER,
    METROLOGY_CONFIG_INVALID_ZERO_RANGE,
    METROLOGY_CONFIG_INVALID_OVERLOAD,
    METROLOGY_CONFIG_INVALID_STABILITY
} MetrologyConfigResult;

MetrologyConfigResult MetrologyConfig_Validate(
    const MetrologyConfig *metrology, const StabilityConfig *stability);

#endif /* METROLOGY_CONFIG_VALIDATOR_H */
