#ifndef DISPLAY_CODES_H
#define DISPLAY_CODES_H

#include <stdbool.h>

typedef enum
{
    DISPLAY_CODE_NOCAL = 0,
    DISPLAY_CODE_UNSTABLE,
    DISPLAY_CODE_ZERO_ERROR,
    DISPLAY_CODE_TARE_ERROR,
    DISPLAY_CODE_OVERLOAD,
    DISPLAY_CODE_CAL_ZERO,
    DISPLAY_CODE_CAL_SPAN,
    DISPLAY_CODE_LOAD,
    DISPLAY_CODE_UNLOAD,
    DISPLAY_CODE_SAVE_QUERY,
    DISPLAY_CODE_NO_SAVE,
    DISPLAY_CODE_RAM_SAVE,
    DISPLAY_CODE_DONE,
    DISPLAY_CODE_CANCEL,
    DISPLAY_CODE_BATTERY,
    DISPLAY_CODE_NET,
    DISPLAY_CODE_GROSS,
    DISPLAY_CODE_TARE,
    DISPLAY_CODE_STATUS,
    DISPLAY_CODE_ERROR,
    DISPLAY_CODE_SAVE,
    DISPLAY_CODE_NO_CHANGE,
    DISPLAY_CODE_SAVE_ERROR,
    DISPLAY_CODE_RESET_QUERY,
    DISPLAY_CODE_RESETTING,
    DISPLAY_CODE_ZERO_RANGE,
    DISPLAY_CODE_BUSY,
    DISPLAY_CODE_INVALID_CONFIG,
    DISPLAY_CODE_UNIT_ERROR,
    DISPLAY_CODE_CALIBRATION_ERROR,
    DISPLAY_CODE_APPLYING,
    DISPLAY_CODE_FLASH_SAVE,
    DISPLAY_CODE_READ_ONLY,
    DISPLAY_CODE_COUNT
} DisplayCode;

#define DISPLAY_CODE_NOT_CALIBRATED DISPLAY_CODE_NOCAL
#define DISPLAY_CODE_NOT_STABLE DISPLAY_CODE_UNSTABLE

bool DisplayCodes_Get(DisplayCode code, char text[6]);

#endif /* DISPLAY_CODES_H */
