import { appendCrc, crc16Modbus } from './crc16-modbus';
import { Int64Value } from '../domain/int64-value';
export const BLE = { version:1, sync0:0xa5, sync1:0x5a, headerSize:12, crcSize:2, maxPayload:128, types:{FAST_WEIGHT:1,SLOW_STATUS:2,CHECKWEIGH_STATUS:3,COMMAND_REQUEST:0x80,COMMAND_RESPONSE:0x81} as const };
export interface BleFrame { version:number; type:number; sequence:number; timestampMs:number; payload:Uint8Array; raw?:Uint8Array }
function u16(b:Uint8Array,o:number){return b[o]|b[o+1]<<8} function u32(b:Uint8Array,o:number){return (b[o]|b[o+1]<<8|b[o+2]<<16|b[o+3]<<24)>>>0}
function put16(b:Uint8Array,o:number,v:number){b[o]=v&255;b[o+1]=(v>>>8)&255} function put32(b:Uint8Array,o:number,v:number){for(let i=0;i<4;i++)b[o+i]=(v>>>(8*i))&255}
export function encodeFrame(type:number, sequence:number, timestampMs:number, payload:Uint8Array): Uint8Array { if(payload.length>BLE.maxPayload) throw new RangeError('payload too large'); const body=new Uint8Array(12+payload.length); body.set([0xa5,0x5a,1,type,payload.length&255,payload.length>>>8],0); put16(body,6,sequence); put32(body,8,timestampMs); body.set(payload,12); return appendCrc(body); }
export function decodeFrame(raw:Uint8Array): BleFrame { if(raw.length<14||raw[0]!==0xa5||raw[1]!==0x5a) throw new Error('invalid frame'); const len=u16(raw,4); if(raw.length!==14+len) throw new Error('length mismatch'); if(raw[2]!==1) throw new Error('unsupported version'); if(![1,2,3,0x80,0x81].includes(raw[3])) throw new Error('unsupported type'); if(crc16Modbus(raw.subarray(0,12+len)) !== u16(raw,12+len)) throw new Error('crc mismatch'); return {version:raw[2],type:raw[3],sequence:u16(raw,6),timestampMs:u32(raw,8),payload:raw.slice(12,12+len),raw:raw.slice()}; }
export interface FastWeight { measurementSequence:number; displayMassUg:Int64Value; operationalNetMassUg:Int64Value; operationalGrossMassUg:Int64Value; tareMassUg:Int64Value; stable:boolean; displayLocked:boolean; overload:boolean; unit:number; decimalPlaces:number; division:number }
export function decodeFast(p:Uint8Array):FastWeight { if(p.length!==42)throw new Error('FAST payload length'); return {measurementSequence:u32(p,0),displayMassUg:Int64Value.fromLittleEndian(p,4),operationalNetMassUg:Int64Value.fromLittleEndian(p,12),operationalGrossMassUg:Int64Value.fromLittleEndian(p,20),tareMassUg:Int64Value.fromLittleEndian(p,28),stable:!!p[36],displayLocked:!!p[37],overload:!!p[38],unit:p[39],decimalPlaces:p[40],division:p[41]}; }
export interface SlowStatus { rawCount:number; filteredRaw:number; uncompensatedGrossMassUg:Int64Value; compensatedGrossMassUg:Int64Value; runtimeDriftOffsetUg:Int64Value; runtimeDriftEnabled:boolean; runtimeDriftState:number; persistentDirty:boolean; capacityUg:Int64Value; overloadThresholdUg:Int64Value; filterMode:number; filterStrength:number; activeProfile:number; appState:number; faultMask:number }
export function decodeSlow(p:Uint8Array):SlowStatus { if(p.length!==59)throw new Error('SLOW payload length'); return {rawCount:p[0]|p[1]<<8|p[2]<<16|p[3]<<24,filteredRaw:p[4]|p[5]<<8|p[6]<<16|p[7]<<24,uncompensatedGrossMassUg:Int64Value.fromLittleEndian(p,8),compensatedGrossMassUg:Int64Value.fromLittleEndian(p,16),runtimeDriftOffsetUg:Int64Value.fromLittleEndian(p,24),runtimeDriftEnabled:!!p[32],runtimeDriftState:p[33],persistentDirty:!!p[34],capacityUg:Int64Value.fromLittleEndian(p,35),overloadThresholdUg:Int64Value.fromLittleEndian(p,43),filterMode:p[51],filterStrength:p[52],activeProfile:p[53],appState:p[54],faultMask:u32(p,55)}; }
export function decodeCheckweigh(p:Uint8Array){if(p.length!==8)throw new Error('CHECKWEIGH payload length');return {state:p[0],flags:p[1],weightSource:p[2],configRevision:u32(p,4)};}
export interface CommandRequest {transactionId:number;operation:number;flags:number;data:Uint8Array} export interface CommandResponse {transactionId:number;operation:number;result:number;detailCode:number;data:Uint8Array}
export function encodeCommandRequest(r:CommandRequest, seq=0, ts=0){const p=new Uint8Array(6+r.data.length);put16(p,0,r.transactionId);p[2]=r.operation;p[3]=r.flags;put16(p,4,r.data.length);p.set(r.data,6);return encodeFrame(0x80,seq,ts,p);}
export function decodeCommandRequest(p:Uint8Array):CommandRequest{if(p.length<6||p.length!==6+u16(p,4))throw new Error('invalid request');return {transactionId:u16(p,0),operation:p[2],flags:p[3],data:p.slice(6)};}
export function encodeCommandResponse(r:CommandResponse,seq=0,ts=0){const p=new Uint8Array(8+r.data.length);put16(p,0,r.transactionId);p[2]=r.operation;p[3]=r.result;put16(p,4,r.detailCode);put16(p,6,r.data.length);p.set(r.data,8);return encodeFrame(0x81,seq,ts,p);}
export function decodeCommandResponse(p:Uint8Array):CommandResponse{if(p.length<8||p.length!==8+u16(p,6))throw new Error('invalid response');return {transactionId:u16(p,0),operation:p[2],result:p[3],detailCode:u16(p,4),data:p.slice(8)};}
export function decodeDeviceInfo(data:Uint8Array){if(data.length!==12)throw new Error('device info length');return {protocolVersion:data[0],firmwareVersion:(data[1]<<8)|data[2],schemaVersion:u16(data,4),registerMapVersion:u16(data,6),capabilities:u32(data,8)};}
export function decodeActiveConfig(data:Uint8Array){if(data.length<55)throw new Error('active config prefix length');return {raw:data.slice(),startupAutoZeroEnable:data.length>=85?!!data[84]:undefined};}
