#ifndef FAULT_MANAGER_H
#define FAULT_MANAGER_H

#include <stdbool.h>
#include <stdint.h>

typedef enum
{
  FAULT_NONE = 0,
  FAULT_CONFIG_INVALID,
  FAULT_EVENT_QUEUE_OVERFLOW,
  FAULT_SCHEDULER_ERROR,
  FAULT_ADC_ERROR,
  FAULT_CS1237_NOT_READY,
  FAULT_CS1237_DATA_ERROR,
  FAULT_CALIBRATION_INVALID,
  FAULT_UART_ERROR,
  FAULT_BATTERY_OVERVOLTAGE,
  FAULT_BATTERY_LOW,
  FAULT_MICROSECOND_TIMER_INIT,
  FAULT_CS1237_CONFIG_ERROR,
  FAULT_CS1237_BUFFER_OVERRUN,
  FAULT_TM1628_COMM_ERROR,
  FAULT_BATTERY_ADC_INVALID,
  FAULT_W02_PWRKEY_SAFETY,
  FAULT_METROLOGY_CONFIG_INVALID,
  FAULT_CALIBRATION_DATA_CORRUPT,
  FAULT_WEIGHT_MATH_OVERFLOW,
  FAULT_UI_KEY_MAP_INVALID,
  FAULT_UI_DISPLAY_ERROR,
  FAULT_CONFIG_APPLY_INCONSISTENT,
  FAULT_UI_STATE_ERROR,
  FAULT_CONFIG_FLASH_LAYOUT,
  FAULT_CONFIG_FLASH_IO,
  FAULT_CONFIG_RECORD_CORRUPT,
  FAULT_CONFIG_SCHEMA_UNSUPPORTED,
  FAULT_CONFIG_SAVE_FAILED,
  FAULT_CONFIG_SAVE_POWER_INTERRUPTED
} FaultCode;

void FaultManager_Init(void);
void FaultManager_Set(FaultCode fault);
void FaultManager_Clear(FaultCode fault);
bool FaultManager_IsActive(FaultCode code);
uint32_t FaultManager_GetActiveMask(void);

#endif /* FAULT_MANAGER_H */
