#ifndef APP_STATE_H
#define APP_STATE_H

typedef enum
{
  APP_STATE_BOOT = 0,
  APP_STATE_SELF_TEST,
  APP_STATE_LOAD_CONFIG,
  APP_STATE_DEVICE_INIT,
  APP_STATE_WARMUP,
  APP_STATE_RUN,
  APP_STATE_DIAGNOSTIC,
  APP_STATE_MENU,
  APP_STATE_CALIBRATION,
  APP_STATE_FAULT
} AppState;

#endif /* APP_STATE_H */
