import { Int64Value } from './int64-value';
export interface DeviceInfo { protocolVersion:number; firmwareVersion:number; schemaVersion:number; registerMapVersion:number; capabilities:number }
export interface WeightSnapshot { displayMassUg:Int64Value; netMassUg:Int64Value; grossMassUg:Int64Value; tareMassUg:Int64Value; stable:boolean; displayLocked:boolean; overload:boolean; unit:number; decimalPlaces:number; division:number; timestampMs:number; dataAgeMs:number }
export interface SlowStatus { rawCount:number; filteredRaw:number; uncompensatedGrossMassUg?:Int64Value; compensatedGrossMassUg?:Int64Value; runtimeDriftOffsetUg?:Int64Value; runtimeDriftEnabled?:boolean; runtimeDriftState?:number; capacityUg:Int64Value; overloadThresholdUg:Int64Value; persistentDirty:boolean; faultMask:number }
export interface CheckweighStatus { state:number; flags:number; weightSource:number; configRevision:number }
export interface ActiveConfig { raw:Uint8Array; startupAutoZeroEnable?:boolean }
export interface CommunicationStatus { transport:'BLE'|'MODBUS_TCP'|'MODBUS_RTU'; connected:boolean; lastError?:string }
export type ConnectionState='CLOSED'|'OPENING_ADAPTER'|'ADAPTER_UNAVAILABLE'|'SCANNING'|'CONNECTING'|'DISCOVERING'|'SUBSCRIBING'|'VERIFYING'|'READY'|'DEGRADED'|'RECONNECT_WAIT'|'DISCONNECTING'|'ERROR'|'INCOMPATIBLE';
export interface ProtocolDiagnostics { sequenceGaps:number;duplicates:number;crcErrors:number;resyncBytes:number;rxNotifications:number;rxBytes:number;frames:number;fastFrames:number;slowFrames:number;checkweighFrames:number;commandSuccess:number;commandTimeouts:number;commandMismatches:number;deviceInfoSuccess:number;deviceInfoTimeout:number;activeConfigSuccess:number;activeConfigTimeout:number;unexpectedDisconnects:number;reconnectAttempts:number;maxStaleMs:number;sessionStartedAt?:number;firstDeviceFoundMs?:number;connectMs?:number;subscribeMs?:number;firstFrameMs?:number;lastDataAt?:number;lastError?:string }
export interface CommandResponse { transactionId:number; operation:number; result:number; detailCode:number; data:Uint8Array }
