#ifndef PERSISTENT_SCHEMA_H
#define PERSISTENT_SCHEMA_H

#include <stdint.h>

#define CONFIG_FLASH_PAGE_SIZE        1024U
#define CONFIG_FLASH_SLOT_SIZE        2048U
#define CONFIG_FLASH_SLOT_A_ADDRESS   0x0801F000UL
#define CONFIG_FLASH_SLOT_B_ADDRESS   0x0801F800UL
#define CONFIG_FLASH_END_ADDRESS      0x08020000UL

#define CONFIG_STORE_MAGIC            0x41333343UL
#define CONFIG_STORE_FORMAT_VERSION   1U
#define CONFIG_STORE_SCHEMA_V1        1U
#define CONFIG_STORE_COMMIT_MARKER    0x434F4D54UL
#define CONFIG_STORE_COMMIT_LOW_HALFWORD  0x4D54U
#define CONFIG_STORE_COMMIT_HIGH_HALFWORD 0x434FU
#define CONFIG_STORE_HEADER_SIZE      32U
#define CONFIG_STORE_PAYLOAD_MAX_SIZE 1984U
#define PERSISTENT_V1_PAYLOAD_SIZE    164U
#define CONFIG_STORE_V1_PAYLOAD_SIZE  PERSISTENT_V1_PAYLOAD_SIZE
#define CONFIG_STORE_V1_BODY_SIZE     \
    (CONFIG_STORE_HEADER_SIZE + PERSISTENT_V1_PAYLOAD_SIZE)
#define CONFIG_RECORD_FLAG_FACTORY_DEFAULT (1UL << 0U)

#define CONFIG_HEADER_CRC_OFFSET      20U
#define CONFIG_COMMIT_OFFSET          (CONFIG_FLASH_SLOT_SIZE - 4U)

#endif /* PERSISTENT_SCHEMA_H */
