import { DeviceInfo, WeightSnapshot, SlowStatus, CheckweighStatus, ActiveConfig, ConnectionState, ProtocolDiagnostics } from '../domain/device-model';
import { BleFrame, decodeCheckweigh, decodeFast, decodeSlow } from '../protocol/ble-codec';
export class DeviceStore {
 state:ConnectionState='CLOSED';deviceInfo?:DeviceInfo;weight?:WeightSnapshot;slow?:SlowStatus;checkweigh?:CheckweighStatus;activeConfig?:ActiveConfig;
 diagnostics:ProtocolDiagnostics=this.emptyDiagnostics();private listeners=new Set<()=>void>();private events:string[]=[];deviceId='';deviceName='';rssi?:number;serviceFound=false;notifyFound=false;writeFound=false;lastFastAt?:number;lastSlowAt?:number;lastCheckweighAt?:number;
 subscribe(listener:()=>void){this.listeners.add(listener);return()=>this.listeners.delete(listener)} notify(){this.listeners.forEach(x=>x())}
 setConnectionState(s:ConnectionState){this.state=s;this.notify()}setDevice(id:string,name:string,rssi?:number){this.deviceId=id;this.deviceName=name;this.rssi=rssi;this.notify()}
 setDiscovery(service:boolean,notify:boolean,write:boolean){this.serviceFound=service;this.notifyFound=notify;this.writeFound=write;this.notify()}
 recordNotification(bytes:number){this.diagnostics.rxNotifications++;this.diagnostics.rxBytes+=bytes}
 recordError(message:string){this.diagnostics.lastError=message;this.events.unshift(`${new Date().toISOString()} ${message}`);this.events=this.events.slice(0,20);this.notify()}
 clearCurrentError(){this.diagnostics.lastError=undefined}
 applyFrame(frame:BleFrame,now=Date.now()){this.diagnostics.frames++;this.diagnostics.lastDataAt=now;if(frame.type===1){const f=decodeFast(frame.payload);this.diagnostics.fastFrames++;this.lastFastAt=now;this.weight={displayMassUg:f.displayMassUg,netMassUg:f.operationalNetMassUg,grossMassUg:f.operationalGrossMassUg,tareMassUg:f.tareMassUg,stable:f.stable,displayLocked:f.displayLocked,overload:f.overload,unit:f.unit,decimalPlaces:f.decimalPlaces,division:f.division,timestampMs:frame.timestampMs,dataAgeMs:0};}else if(frame.type===2){this.diagnostics.slowFrames++;this.lastSlowAt=now;this.slow=decodeSlow(frame.payload);}else if(frame.type===3){this.diagnostics.checkweighFrames++;this.lastCheckweighAt=now;this.checkweigh=decodeCheckweigh(frame.payload);}this.notify()}
 syncParser(stats:{crcErrors:number;resyncBytes:number;sequenceGaps:number;duplicates:number},emit=true){this.diagnostics.crcErrors=stats.crcErrors;this.diagnostics.resyncBytes=stats.resyncBytes;this.diagnostics.sequenceGaps=stats.sequenceGaps;this.diagnostics.duplicates=stats.duplicates;if(emit)this.notify()}
 updateAges(now=Date.now()){if(this.weight&&this.lastFastAt)this.weight.dataAgeMs=now-this.lastFastAt;this.notify()}
 get fastStale(){return !this.lastFastAt||Date.now()-this.lastFastAt>1000}get fastInvalid(){return !this.lastFastAt||Date.now()-this.lastFastAt>3000}get slowStale(){return !this.lastSlowAt||Date.now()-this.lastSlowAt>3000}get checkweighStale(){return !this.lastCheckweighAt||Date.now()-this.lastCheckweighAt>3000}
 clearSessionStatistics(){const previous=this.diagnostics;this.diagnostics=this.emptyDiagnostics();this.diagnostics.lastError=previous.lastError;this.diagnostics.firstDeviceFoundMs=previous.firstDeviceFoundMs;this.diagnostics.connectMs=previous.connectMs;this.diagnostics.subscribeMs=previous.subscribeMs;this.diagnostics.sessionStartedAt=Date.now();this.events=[];this.notify()}
 diagnosticEvents(){return [...this.events]}diagnosticSummary(){const capturedAt=Date.now();return JSON.stringify({capturedAt,durationS:this.diagnostics.sessionStartedAt?Math.floor((capturedAt-this.diagnostics.sessionStartedAt)/1000):null,state:this.state,deviceId:this.deviceId,name:this.deviceName,rssi:this.rssi,service:this.serviceFound,notify:this.notifyFound,write:this.writeFound,deviceInfo:this.deviceInfo,lastFastAt:this.lastFastAt,lastSlowAt:this.lastSlowAt,lastCheckweighAt:this.lastCheckweighAt,diagnostics:this.diagnostics},null,2)}
 private emptyDiagnostics():ProtocolDiagnostics{return {sequenceGaps:0,duplicates:0,crcErrors:0,resyncBytes:0,rxNotifications:0,rxBytes:0,frames:0,fastFrames:0,slowFrames:0,checkweighFrames:0,commandSuccess:0,commandTimeouts:0,commandMismatches:0,deviceInfoSuccess:0,deviceInfoTimeout:0,activeConfigSuccess:0,activeConfigTimeout:0,unexpectedDisconnects:0,reconnectAttempts:0,maxStaleMs:0}}
}
