#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#define BOARD_NAME                    "STM32F103RBT6_A33"
#define BOARD_HW_VERSION              "A33"
#define BOARD_FW_ARCH_VERSION         "1.0"

#define FW_ARCH_VERSION_MAJOR         1U
#define FW_ARCH_VERSION_MINOR         0U
#define DEVICE_CONFIG_SCHEMA_VERSION  2U

#define SYSTEM_TICK_HZ                1000U
#define SCHEDULER_MAX_TASKS           8U
#define EVENT_QUEUE_CAPACITY          16U
#define APP_MAX_EVENTS_PER_RUN        8U
#define CS1237_SAMPLE_BUFFER_CAPACITY 16U
#define MEASUREMENT_BRIDGE_MAX_SAMPLES_PER_RUN 4U
#define RAW_MEASUREMENT_EVENT_PERIOD_MS 20U
#define WEIGHT_MEASUREMENT_EVENT_PERIOD_MS 20U

#define PROJECT_ENABLE_IWDG           0U
#define PROJECT_ENABLE_USB_RESERVED   0U
#define ENABLE_STAGE2A_DIAGNOSTICS    0U
#ifndef ENABLE_STAGE2B_BOARD_DIAGNOSTICS
#define ENABLE_STAGE2B_BOARD_DIAGNOSTICS 1U
#endif
#define STAGE2B_DIAG_AUTO_INTERNAL_BEEP 0U
#define STAGE2B_DIAG_PAGE_PERIOD_MS   2000U
#define STAGE2B_DIAG_KEY_HOLD_MS      1000U
#define STAGE2B_DIAG_STARTUP_BLANK_MS 300U
#define STAGE2B_DIAG_STEP_PERIOD_MS   300U
#ifndef CS1237_OVERRUN_FATAL
#define CS1237_OVERRUN_FATAL          1U
#endif

#define BSP_DELAY_US_MAX              1000U
#define W02_PWRKEY_MIN_PULSE_MS       50U
#define W02_PWRKEY_MAX_PULSE_MS       200U
#define W02_PWRKEY_DEFAULT_PULSE_MS   80U
#define W02_PWRKEY_HARD_LIMIT_MS      250U
#define W02_PWRKEY_MAX_ASSERT_MS      W02_PWRKEY_HARD_LIMIT_MS

#define CS1237_EXTERNAL_ENABLE_PRESENT 1U
#define CS1237_ENABLE_ACTIVE_LEVEL     1U
/* Confirmed by the hardware owner: PB12 high enables, low disables. */
#define CS1237_ENABLE_POLARITY_CONFIRMED 1U
/* REFOUT drives the board reference path and must remain enabled. */
#define CS1237_REFERENCE_OUTPUT_ENABLED 1U
#if (CS1237_REFERENCE_OUTPUT_ENABLED != 1U)
#error "Current A33 hardware requires CS1237 internal REFOUT."
#endif
#define CS1237_SCLK_HALF_PERIOD_US     1U
#define CS1237_POWER_UP_WAIT_MS        10U
#define CS1237_SETTLING_SAMPLES_10HZ   4U
#define CS1237_SETTLING_SAMPLES_40HZ   4U
#define CS1237_SETTLING_SAMPLES_640HZ  4U
#define CS1237_SETTLING_SAMPLES_1280HZ 4U

#define TM1628_RAM_SIZE                14U
#define TM1628_GRID_COUNT              7U
#define BOARD_DISPLAY_DIGIT_COUNT      6U
#define TM1628_SERIAL_HALF_PERIOD_US   1U
#define TM1628_COMMAND_WAIT_US         2U
#define DRIVER_CONSECUTIVE_ERROR_LIMIT 3U
#define APP_DRIVER_WARMUP_TIMEOUT_MS   3000U

#define BATTERY_ADC_FULL_SCALE        4095U
#define BATTERY_ADC_SAMPLE_COUNT       8U
#define BATTERY_ADC_NEAR_FULL_SCALE_RAW 4000U
#define BATTERY_DIVIDER_TOP_OHM       30000U
#define BATTERY_DIVIDER_BOTTOM_OHM    10000U
#define BATTERY_DEFAULT_VDDA_MV       3300U

#endif
