import { WxBleAdapter, BleAdapter, BleDevice } from './ble-adapter';import { BleConnectionManager } from './ble-connection-manager';import { BleWriteQueue } from './ble-write-queue';import { BleCommandClient } from './ble-command-client';import { DeviceStore } from '../store/device-store';import { BleFrame, decodeActiveConfig, decodeDeviceInfo } from '../protocol/ble-codec';
export class BleMonitorService {
 readonly store=new DeviceStore();readonly manager:BleConnectionManager;devices:BleDevice[]=[];private command?:BleCommandClient;private staleTimer?:ReturnType<typeof setInterval>;private reconnectTimer?:ReturnType<typeof setTimeout>;private reconnectAttempts=0;private disposed=false;
 constructor(private readonly adapter:BleAdapter=new WxBleAdapter()){this.manager=new BleConnectionManager(adapter,{onState:s=>this.onState(s),onDevices:d=>{this.devices=d;this.store.notify()},onNotification:n=>this.store.recordNotification(n),onDiscovery:(s,n,w)=>this.store.setDiscovery(s,n,w),onTiming:(name,value)=>{this.store.diagnostics[name]=value;this.store.notify()},onError:e=>this.store.recordError(e),onFrame:f=>this.onFrame(f),verify:()=>this.verifyDevice()})}
 async initialize(){this.disposed=false;await this.manager.initialize();this.startStaleTimer()}scan(){return this.manager.scan(10000)}stopScan(){return this.manager.stopScan()}
 async connect(device:BleDevice){this.reconnectAttempts=0;this.store.setDevice(device.deviceId,device.name||device.localName||'Unknown W02',device.RSSI);await this.manager.connect(device)}
 async disconnect(){this.cancelReconnect();this.command?.cancel('User disconnected');await this.manager.disconnect()}
 async dispose(){this.disposed=true;this.cancelReconnect();if(this.staleTimer)clearInterval(this.staleTimer);this.staleTimer=undefined;this.command?.cancel('Page disposed');await this.manager.dispose()}
 private onState(state:any){if(state==='RECONNECT_WAIT')this.store.diagnostics.unexpectedDisconnects++;this.store.setConnectionState(state);if(state==='READY')this.cancelReconnect();if(state==='RECONNECT_WAIT'||(state==='ERROR'&&this.reconnectAttempts>0))this.scheduleReconnect();if(state==='CLOSED'||state==='ERROR'||state==='INCOMPATIBLE'||state==='RECONNECT_WAIT')this.command?.cancel(`Connection state ${state}`)}
 private configureCommand(){const m=this.manager;if(!m.selected||!m.serviceUuid||!m.writeUuid)throw new Error('BLE write characteristic unavailable');this.command=new BleCommandClient(new BleWriteQueue(this.adapter,m.selected.deviceId,m.serviceUuid,m.writeUuid,m.writeWithResponse),2000)}
 private async verifyDevice(){try{this.configureCommand();this.store.deviceInfo=decodeDeviceInfo((await this.readCommand(1)).data);if(this.store.deviceInfo.protocolVersion!==1||this.store.deviceInfo.firmwareVersion!==0x050a||this.store.deviceInfo.schemaVersion!==2||this.store.deviceInfo.registerMapVersion!==0x0104){this.store.recordError('Incompatible BLE protocol or firmware contract');return false}this.store.activeConfig=decodeActiveConfig((await this.readCommand(2)).data);this.syncCommandMetrics();this.store.notify();return true}catch(e){this.store.recordError((e as Error).message);this.syncCommandMetrics();return false}}
 async refreshReadOnly(){if(!this.command)throw new Error('Device is not ready');this.store.deviceInfo=decodeDeviceInfo((await this.readCommand(1)).data);this.store.activeConfig=decodeActiveConfig((await this.readCommand(2)).data);this.syncCommandMetrics();this.store.notify()}
 clearStatistics(){this.manager.parser.resetStatistics();this.command?.metrics&&(this.command.metrics.success=0,this.command.metrics.timeouts=0,this.command.metrics.mismatches=0);this.store.clearSessionStatistics()}
 private async readCommand(operation:1|2){if(!this.command)throw new Error('Device is not ready');try{const response=await this.command.request(operation);if(operation===1)this.store.diagnostics.deviceInfoSuccess++;else this.store.diagnostics.activeConfigSuccess++;return response}catch(e){if(/timeout/i.test((e as Error).message)){if(operation===1)this.store.diagnostics.deviceInfoTimeout++;else this.store.diagnostics.activeConfigTimeout++}throw e}}
 private onFrame(frame:BleFrame){this.command?.onFrame(frame);const telemetry=frame.type===1||frame.type===2||frame.type===3;if(telemetry&&this.store.diagnostics.sessionStartedAt&&!this.store.diagnostics.firstFrameMs)this.store.diagnostics.firstFrameMs=Date.now()-this.store.diagnostics.sessionStartedAt;this.store.syncParser(this.manager.parser.stats,!telemetry);if(telemetry)this.store.applyFrame(frame);this.syncCommandMetrics();if(this.store.state==='DEGRADED')this.manager.markRecovered()}
 private syncCommandMetrics(){if(!this.command)return;this.store.diagnostics.commandSuccess=this.store.diagnostics.deviceInfoSuccess+this.store.diagnostics.activeConfigSuccess;this.store.diagnostics.commandTimeouts=this.command.metrics.timeouts;this.store.diagnostics.commandMismatches=this.command.metrics.mismatches}
 private startStaleTimer(){if(this.staleTimer)return;this.staleTimer=setInterval(()=>{this.store.updateAges();const connected=this.store.state==='READY'||this.store.state==='DEGRADED';const age=this.store.diagnostics.lastDataAt?Date.now()-this.store.diagnostics.lastDataAt:0;if(connected&&age>this.store.diagnostics.maxStaleMs)this.store.diagnostics.maxStaleMs=age;if(connected&&age>5000)this.manager.markDegraded()},500)}
 private scheduleReconnect(){if(this.disposed||!this.manager.selected||this.reconnectAttempts>=3)return;const device=this.manager.selected;this.reconnectAttempts++;this.store.diagnostics.reconnectAttempts++;this.reconnectTimer=setTimeout(()=>this.manager.connect(device),Math.min(1000*this.reconnectAttempts,3000))}
 private cancelReconnect(){if(this.reconnectTimer)clearTimeout(this.reconnectTimer);this.reconnectTimer=undefined;this.reconnectAttempts=0}
}
let singleton:BleMonitorService|undefined;export function bleMonitorService(){return singleton??=(new BleMonitorService())}
