import { BleAdapter, BleDevice, normalizeUuid } from './ble-adapter';
import { BleStreamParser } from './ble-stream-parser';
import { BleFrame } from '../protocol/ble-codec';
import { BleAdapterError, ConnectionState } from './ble-types';
export { ConnectionState } from './ble-types';

export interface ConnectionCallbacks { onState?:(s:ConnectionState)=>void;onDevices?:(d:BleDevice[])=>void;onFrame?:(f:BleFrame)=>void;onNotification?:(bytes:number)=>void;onDiscovery?:(service:boolean,notify:boolean,write:boolean)=>void;onTiming?:(name:'firstDeviceFoundMs'|'connectMs'|'subscribeMs',value:number)=>void;onError?:(message:string)=>void;verify?:()=>Promise<boolean> }
export class BleConnectionManager {
  state:ConnectionState='CLOSED'; devices:BleDevice[]=[]; parser=new BleStreamParser(); selected?:BleDevice;
  serviceUuid=''; notifyUuid=''; writeUuid=''; writeWithResponse=true;
  private operation?:'scan'|'connect'|'disconnect';private scanTimer?:ReturnType<typeof setTimeout>;private generation=0;private intentionalDisconnect=false;private initialized=false;private scanStartedAt=0;private connectStartedAt=0;private firstDeviceReported=false;private offAdapter?:()=>void;private offConnection?:()=>void;
  constructor(private readonly adapter:BleAdapter,private readonly callbacks:ConnectionCallbacks={}){}
  private set(s:ConnectionState){this.state=s;this.callbacks.onState?.(s)} private fail(message:string,state:ConnectionState='ERROR'){this.callbacks.onError?.(message);this.set(state)}
  private adapterErrorMessage(error:unknown){if(error instanceof BleAdapterError){if(error.kind==='PERMISSION_DENIED')return '附近设备/蓝牙权限被拒绝，请在系统设置中授权';if(error.kind==='BLUETOOTH_OFF')return '手机蓝牙已关闭，请开启蓝牙';if(error.kind==='UNSUPPORTED')return '当前环境不支持 BLE，请使用真机';}return (error as Error).message}
  async initialize(forceOpen=false){if(this.initialized&&!forceOpen&&this.state!=='ADAPTER_UNAVAILABLE'&&this.state!=='ERROR')return;if(this.state!=='CLOSED'&&this.state!=='ADAPTER_UNAVAILABLE'&&this.state!=='ERROR')return;this.set('OPENING_ADAPTER');try{await this.adapter.open();if(!this.initialized){this.offAdapter=this.adapter.onAdapterStateChange(s=>{if(!s.available){this.generation++;if(this.scanTimer)clearTimeout(this.scanTimer);this.scanTimer=undefined;void this.adapter.stopDiscovery();this.clearConnectionDetails();this.fail('Bluetooth adapter unavailable','ADAPTER_UNAVAILABLE')}else if(this.state==='ADAPTER_UNAVAILABLE'){this.set('CLOSED')}});this.offConnection=this.adapter.onConnectionStateChange(e=>{if(this.selected&&e.deviceId===this.selected.deviceId&&!e.connected&&!this.intentionalDisconnect){this.generation++;this.fail('BLE connection lost','RECONNECT_WAIT')}});this.initialized=true}this.set('CLOSED')}catch(e){this.fail(this.adapterErrorMessage(e),'ADAPTER_UNAVAILABLE')}}
  async scan(timeoutMs=10000){if(this.operation||this.state==='SCANNING')return;this.operation='scan';try{if(this.state==='CLOSED'||this.state==='ERROR'||this.state==='ADAPTER_UNAVAILABLE')await this.initialize(true);if(this.state!=='CLOSED')return;this.devices=[];this.scanStartedAt=Date.now();this.firstDeviceReported=false;this.set('SCANNING');await this.adapter.startDiscovery(d=>this.upsertDevice(d));this.scanTimer=setTimeout(()=>this.stopScan(),timeoutMs)}catch(e){this.fail((e as Error).message)}finally{this.operation=undefined}}
  private upsertDevice(device:BleDevice){if(!this.firstDeviceReported){this.firstDeviceReported=true;this.callbacks.onTiming?.('firstDeviceFoundMs',Date.now()-this.scanStartedAt)}const index=this.devices.findIndex(x=>x.deviceId===device.deviceId);const merged={...(index>=0?this.devices[index]:{}),...device,lastSeenAt:Date.now()};if(index>=0)this.devices[index]=merged;else this.devices.push(merged);this.devices.sort((a,b)=>Number((b.name||b.localName||'').startsWith('W02_'))-Number((a.name||a.localName||'').startsWith('W02_'))||(b.RSSI??-999)-(a.RSSI??-999));this.callbacks.onDevices?.([...this.devices])}
  async stopScan(){if(this.scanTimer)clearTimeout(this.scanTimer);this.scanTimer=undefined;await this.adapter.stopDiscovery().catch(()=>{});if(this.state==='SCANNING')this.set('CLOSED')}
  private isClosed(){return this.state==='CLOSED'}
  async connect(device:BleDevice){if(this.operation||['CONNECTING','DISCOVERING','SUBSCRIBING','VERIFYING','READY'].includes(this.state))return;if(this.state==='CLOSED'||this.state==='ADAPTER_UNAVAILABLE'||this.state==='ERROR'){await this.initialize(true);if(!this.isClosed())return}this.operation='connect';const generation=++this.generation;this.connectStartedAt=Date.now();try{await this.stopScan();this.selected=device;this.intentionalDisconnect=false;this.parser=new BleStreamParser();this.set('CONNECTING');await this.adapter.connect(device.deviceId,8000);this.callbacks.onTiming?.('connectMs',Date.now()-this.connectStartedAt);if(generation!==this.generation)return;this.set('DISCOVERING');const services=await this.adapter.discoverServices(device.deviceId);this.serviceUuid=services.find(s=>normalizeUuid(s)==='ffe0')||'';if(!this.serviceUuid){this.callbacks.onDiscovery?.(false,false,false);this.fail('FFE0 service not found','INCOMPATIBLE');return}const chars=await this.adapter.discoverCharacteristics(device.deviceId,this.serviceUuid);const notify=chars.find(c=>normalizeUuid(c.uuid)==='ffe1'&&(c.properties.notify||c.properties.indicate));const write=chars.find(c=>normalizeUuid(c.uuid)==='ffe2'&&(c.properties.write||c.properties.writeNoResponse));this.callbacks.onDiscovery?.(true,!!notify,!!write);if(!notify||!write){this.fail('Required FFE1 Notify or FFE2 Write characteristic not found','INCOMPATIBLE');return}this.notifyUuid=notify.uuid;this.writeUuid=write.uuid;this.writeWithResponse=!!write.properties.write;this.set('SUBSCRIBING');const subscribeStartedAt=Date.now();await this.adapter.subscribe(device.deviceId,this.serviceUuid,this.notifyUuid,data=>{if(generation!==this.generation)return;this.callbacks.onNotification?.(data.length);for(const frame of this.parser.push(data))this.callbacks.onFrame?.(frame)});this.callbacks.onTiming?.('subscribeMs',Date.now()-subscribeStartedAt);this.set('VERIFYING');if(this.callbacks.verify&&!(await this.callbacks.verify())){this.set('INCOMPATIBLE');return}this.set('READY')}catch(e){if(generation===this.generation)this.fail((e as Error).message)}finally{this.operation=undefined}}
  markDegraded(){if(this.state==='READY')this.set('DEGRADED')} markRecovered(){if(this.state==='DEGRADED')this.set('READY')}
  private clearConnectionDetails(){this.selected=undefined;this.serviceUuid='';this.notifyUuid='';this.writeUuid='';this.callbacks.onDiscovery?.(false,false,false)}
  async disconnect(){if(this.operation==='disconnect')return;this.operation='disconnect';this.intentionalDisconnect=true;this.set('DISCONNECTING');this.generation++;try{await this.stopScan();if(this.selected)await this.adapter.disconnect(this.selected.deviceId)}finally{this.clearConnectionDetails();this.set('CLOSED');this.operation=undefined}}
  async dispose(){await this.disconnect();this.offAdapter?.();this.offConnection?.();this.adapter.dispose();this.initialized=false}
}
