#ifndef MENU_TYPES_H
#define MENU_TYPES_H

#include "project_config.h"

typedef enum
{
    MENU_ITEM_UNIT = 0,
    MENU_ITEM_PROFILE,
    MENU_ITEM_CALIBRATION,
    MENU_ITEM_CAPACITY,
    MENU_ITEM_DIVISION,
    MENU_ITEM_DECIMALS,
    MENU_ITEM_FILTER,
    MENU_ITEM_STABILITY,
    MENU_ITEM_ZERO_RANGE,
    MENU_ITEM_OVERLOAD,
    MENU_ITEM_BRIGHTNESS,
    MENU_ITEM_SAMPLE_RATE,
    MENU_ITEM_GAIN,
    MENU_ITEM_TARE_RETENTION,
#if (ENABLE_STAGE5E_A3_LOCAL_MENU != 0U)
    MENU_ITEM_LIMIT_ENABLE,
    MENU_ITEM_ALARM_LOWER_LIMIT,
    MENU_ITEM_ALARM_UPPER_LIMIT,
    MENU_ITEM_ALARM_HYSTERESIS,
    MENU_ITEM_ALARM_SOURCE,
    MENU_ITEM_INTERNAL_BUZZER,
    MENU_ITEM_EXTERNAL_BUZZER,
    MENU_ITEM_QUALIFIED_BEEP,
#endif
    MENU_ITEM_SAVE,
    MENU_ITEM_FACTORY_RESET,
    MENU_ITEM_EXIT,
    MENU_ITEM_COUNT
} MenuItem;

#endif /* MENU_TYPES_H */
