#ifndef MENU_TYPES_H
#define MENU_TYPES_H

typedef enum
{
    MENU_ITEM_CALIBRATION = 0,
    MENU_ITEM_CAPACITY,
    MENU_ITEM_DIVISION,
    MENU_ITEM_DECIMALS,
    MENU_ITEM_FILTER,
    MENU_ITEM_STABILITY,
    MENU_ITEM_ZERO_RANGE,
    MENU_ITEM_OVERLOAD,
    MENU_ITEM_BRIGHTNESS,
    MENU_ITEM_SAMPLE_RATE,
    MENU_ITEM_GAIN,
    MENU_ITEM_TARE_RETENTION,
    MENU_ITEM_SAVE,
    MENU_ITEM_EXIT,
    MENU_ITEM_COUNT
} MenuItem;

#endif /* MENU_TYPES_H */
