using A33.Instrument.Protocol;

namespace A33.Instrument.Core;

public enum RuntimeOperation { Zero, Tare, ClearTare, SetNetView, SetGrossView }
public enum CommandExecutionState { Idle, Validating, WaitingForTransport, Sending, WaitingForProtocolResponse, WaitingForCommandResult, VerifyingState, Succeeded, Rejected, Failed, ResultUncertain }
public sealed record CommandAuditEntry(DateTimeOffset StartedAt,DateTimeOffset CompletedAt,TransportMode Transport,string Endpoint,byte UnitId,RuntimeOperation Operation,ushort TransactionId,byte Function,byte[] RequestSummary,byte[] ResponseSummary,ushort ResultCode,CommandExecutionState FinalState,string StateReadback,double DurationMs,bool Uncertain);
public sealed record RuntimeCommandResult(RuntimeOperation Operation,ushort TransactionId,ushort ResultCode,CommandExecutionState State,string Message,bool StateReadbackCompleted,InstrumentSnapshot? Snapshot,CommandAuditEntry Audit);

public sealed class RuntimeCommandService(InstrumentMonitoringService monitoring)
{
    private readonly SemaphoreSlim gate=new(1,1);private ushort nextToken=1;private readonly Queue<CommandAuditEntry> audit=new();private readonly object auditSync=new();
    public CommandExecutionState State{get;private set;}=CommandExecutionState.Idle;public ushort CurrentTransactionId{get;private set;}public RuntimeCommandResult? LastResult{get;private set;}public IReadOnlyList<CommandAuditEntry> Audit{get{lock(auditSync)return audit.ToArray();}}public event EventHandler? StateChanged;
    public bool CanExecute=>State==CommandExecutionState.Idle&&LastResult?.State!=CommandExecutionState.ResultUncertain&&monitoring.State==MonitoringConnectionState.Monitoring&&!monitoring.IsStale&&monitoring.MapVersion==RegisterMap.Version&&monitoring.Snapshot is not null;
    public async Task<RuntimeCommandResult> ExecuteAsync(RuntimeOperation operation,CancellationToken cancellationToken=default)
    {
        if(!CanExecute)throw new InvalidOperationException("Runtime operation requires a fresh MONITORING connection.");if(!await gate.WaitAsync(0,cancellationToken))throw new InvalidOperationException("Another runtime operation is already in progress.");
        var started=DateTimeOffset.Now;var token=NextToken();CurrentTransactionId=token;State=CommandExecutionState.Validating;RuntimeCommandResult? result=null;byte[] request=[];byte[] response=[];var readback="not started";var uncertain=false;ushort resultCode=0;
        try{if(monitoring.Snapshot is null||monitoring.IsStale)throw new InvalidOperationException("Weight snapshot became stale before command submission.");var commandId=operation switch{RuntimeOperation.Zero=>1,RuntimeOperation.Tare=>3,RuntimeOperation.ClearTare=>4,RuntimeOperation.SetNetView=>5,RuntimeOperation.SetGrossView=>5,_=>throw new ArgumentOutOfRangeException(nameof(operation))};var argument=operation switch{RuntimeOperation.SetNetView=>0,RuntimeOperation.SetGrossView=>1,_=>0};State=CommandExecutionState.WaitingForTransport;var words=new ushort[12];words[0]=token;words[1]=(ushort)commandId;words[2]=(ushort)(argument>>16);words[3]=(ushort)argument;words[10]=0;words[11]=0xA55A;State=CommandExecutionState.Sending;var sequence=await monitoring.WithCommandExclusiveAsync(async c=>{var exchange=await c.WriteMultipleAsync(0x0040,words,cancellationToken);var mailbox=await c.ReadHoldingAsync(0x004C,12,cancellationToken);ushort[]? values=null;if(mailbox[0]==token&&mailbox[3]==(ushort)commandId&&mailbox[1]==0){State=CommandExecutionState.VerifyingState;values=await c.ReadHoldingAsync(0,34,cancellationToken);}return (exchange,mailbox,values);},cancellationToken);request=sequence.exchange.RequestAdu;response=sequence.exchange.ResponseAdu;State=CommandExecutionState.WaitingForCommandResult;var mailbox=sequence.mailbox;if(mailbox[0]!=token||mailbox[3]!=(ushort)commandId){uncertain=true;State=CommandExecutionState.ResultUncertain;readback=$"response token/command mismatch: token 0x{mailbox[0]:X4}, command {mailbox[3]}";}else{resultCode=mailbox[1];if(resultCode!=0){State=CommandExecutionState.Rejected;readback=$"device result {resultCode}";}else{State=CommandExecutionState.VerifyingState;var values=sequence.values??throw new InvalidOperationException("State readback was not returned.");var snapshot=InstrumentRegisterDecoder.DecodeRealtime(0,values,monitoring.WordOrder,monitoring.Snapshot);readback=VerifyReadback(operation,snapshot,values);monitoring.ReplaceSnapshot(snapshot);State=readback=="OK"?CommandExecutionState.Succeeded:CommandExecutionState.ResultUncertain;if(State==CommandExecutionState.ResultUncertain)uncertain=true;result=new RuntimeCommandResult(operation,token,resultCode,State,State==CommandExecutionState.Succeeded?"操作成功并完成状态读回":"设备已返回成功，但状态读回与预期不一致",true,snapshot,BuildAudit(started,operation,token,request,response,resultCode,readback,uncertain));}}
            if(result is null){var message=uncertain?"命令可能已被仪表执行，但客户端没有取得最终结果。请重新读取仪表状态，确认后再决定是否操作。":$"仪表拒绝操作，Result Code {resultCode}";result=new RuntimeCommandResult(operation,token,resultCode,State,message,false,monitoring.Snapshot,BuildAudit(started,operation,token,request,response,resultCode,readback,uncertain));}
            LastResult=result;return result;
        }catch(OperationCanceledException)when(cancellationToken.IsCancellationRequested){State=request.Length>0?CommandExecutionState.ResultUncertain:CommandExecutionState.Failed;uncertain=request.Length>0;var message=uncertain?"命令可能已被仪表执行，但客户端没有取得最终结果。请重新读取仪表状态，确认后再决定是否操作。":"操作在发送前被取消";result=new RuntimeCommandResult(operation,token,resultCode,State,message,false,monitoring.Snapshot,BuildAudit(started,operation,token,request,response,resultCode,readback,uncertain));LastResult=result;return result;}catch(Exception error){State=request.Length>0?CommandExecutionState.ResultUncertain:CommandExecutionState.Failed;uncertain=request.Length>0;var message=uncertain?"命令可能已被仪表执行，但客户端没有取得最终结果。请重新读取仪表状态，确认后再决定是否操作。":error.Message;result=new RuntimeCommandResult(operation,token,resultCode,State,message,false,monitoring.Snapshot,BuildAudit(started,operation,token,request,response,resultCode,error.Message,uncertain));LastResult=result;return result;}finally{CurrentTransactionId=0;State=CommandExecutionState.Idle;StateChanged?.Invoke(this,EventArgs.Empty);gate.Release();}
    }
    public void ClearAudit(){lock(auditSync)audit.Clear();}
    public async Task RefreshStateAsync(CancellationToken cancellationToken=default){var values=await monitoring.WithCommandExclusiveAsync(c=>c.ReadHoldingAsync(0,34,cancellationToken),cancellationToken);monitoring.ReplaceSnapshot(InstrumentRegisterDecoder.DecodeRealtime(0,values,monitoring.WordOrder,monitoring.Snapshot));if(LastResult?.State==CommandExecutionState.ResultUncertain)LastResult=null;State=CommandExecutionState.Idle;StateChanged?.Invoke(this,EventArgs.Empty);}
    private ushort NextToken(){var value=nextToken++;if(value==0)value=nextToken++;return value;}
    private static string VerifyReadback(RuntimeOperation operation,InstrumentSnapshot snapshot,ushort[] values){if(!snapshot.Stable)return "readback not stable";if(operation==RuntimeOperation.ClearTare&&snapshot.TareMassUg!=0)return "TARE value was not cleared";if(operation==RuntimeOperation.SetNetView&&values[13]!=0)return "weight view is not NET";if(operation==RuntimeOperation.SetGrossView&&values[13]!=1)return "weight view is not GROSS";if(operation==RuntimeOperation.Zero&&!snapshot.Zero)return "zero status was not set";return "OK";}
    private CommandAuditEntry BuildAudit(DateTimeOffset started,RuntimeOperation operation,ushort token,byte[] request,byte[] response,ushort code,string readback,bool uncertain){var options=monitoring.CurrentOptions;var entry=new CommandAuditEntry(started,DateTimeOffset.Now,options?.Mode??TransportMode.Tcp,monitoring.Endpoint,options?.UnitId??1,operation,token,0x10,Bounded(request),Bounded(response),code,State,readback,(DateTimeOffset.Now-started).TotalMilliseconds,uncertain);lock(auditSync){audit.Enqueue(entry);while(audit.Count>200)audit.Dequeue();}return entry;}
    private static byte[] Bounded(byte[] data)=>data.Length<=128?data.ToArray():data[..128];
}
