using A33.Instrument.Core;
using A33.Instrument.Protocol;
using System.Net;
using System.Net.Sockets;
using Xunit;

namespace A33.Instrument.Protocol.Tests;

public class CoreTests
{
    [Fact] public async Task CompatibleMapConnects(){var transport=MockTransport.Healthy();await using var service=new InstrumentMonitoringService(new QueueFactory(transport));await service.ConnectAsync(Options());Assert.Equal(MonitoringConnectionState.Connected,service.State);Assert.Equal((ushort)0x0104,service.MapVersion);Assert.Equal(WordOrder.HighWordFirst,service.WordOrder);}
    [Fact] public async Task IncompatibleMapRefusesMonitoring(){var transport=MockTransport.Healthy(0x0103);await using var service=new InstrumentMonitoringService(new QueueFactory(transport));await Assert.ThrowsAsync<InvalidOperationException>(()=>service.ConnectAsync(Options()));Assert.Equal(MonitoringConnectionState.Faulted,service.State);Assert.Single(transport.Requests);await Assert.ThrowsAsync<InvalidOperationException>(async()=>await service.StartMonitoringAsync());}
    [Fact] public async Task ClientAllowsOnlyOneRequestInFlight(){var transport=MockTransport.Healthy(delayMs:20);await transport.OpenAsync(default);var client=new ReadOnlyModbusClient(transport,1,TimeSpan.FromSeconds(1));await Task.WhenAll(client.ReadHoldingAsync(14,1),client.ReadHoldingAsync(14,1));Assert.Equal(1,transport.MaxConcurrent);}
    [Fact] public async Task MonitoringUsesOnlyFc03AndStopsSending(){var transport=MockTransport.Healthy();await using var service=new InstrumentMonitoringService(new QueueFactory(transport));await service.ConnectAsync(Options());await service.StartMonitoringAsync();await Task.Delay(350);await service.StopMonitoringAsync();var count=transport.Requests.Count;await Task.Delay(250);Assert.Equal(count,transport.Requests.Count);Assert.All(transport.Requests,p=>Assert.Equal((byte)3,p.Span[0]));Assert.NotNull(service.Snapshot);}
    [Fact] public async Task TimeoutDegradesThenRecoversAndRetainsSnapshot(){var transport=MockTransport.Healthy();var realtimeCalls=0;transport.BeforeResponse=p=>{if(Address(p)==0&&++realtimeCalls==2)throw new OperationCanceledException("request timeout");};await using var service=new InstrumentMonitoringService(new QueueFactory(transport));await service.ConnectAsync(Options());await service.StartMonitoringAsync();await Task.Delay(700);Assert.NotNull(service.Snapshot);Assert.True(service.Diagnostics.Timeouts>=1);Assert.Equal(MonitoringConnectionState.Monitoring,service.State);}
    [Fact] public async Task UserDisconnectDoesNotReconnect(){var transport=MockTransport.Healthy();var factory=new QueueFactory(transport);await using var service=new InstrumentMonitoringService(factory);await service.ConnectAsync(Options());await service.StartMonitoringAsync();await service.DisconnectAsync();await Task.Delay(150);Assert.Equal(1,factory.CreateCount);Assert.Equal(MonitoringConnectionState.Disconnected,service.State);}
    [Fact] public async Task TransportFailureRetriesThreeTimesThenFaults(){var initial=MockTransport.Healthy();initial.BeforeResponse=p=>{if(Address(p)==0)throw new IOException("link lost");};var factory=new QueueFactory(initial,MockTransport.OpenFailure(),MockTransport.OpenFailure(),MockTransport.OpenFailure());await using var service=new InstrumentMonitoringService(factory);await service.ConnectAsync(Options());await service.StartMonitoringAsync();await WaitForAsync(()=>service.State==MonitoringConnectionState.Faulted,TimeSpan.FromSeconds(6));Assert.Equal(3,service.Diagnostics.Reconnects);Assert.Equal(4,factory.CreateCount);}
    [Fact] public void DiagnosticsLogIsBounded(){var d=new CommunicationDiagnostics();for(var i=0;i<250;i++)d.Add($"entry {i}");Assert.Equal(200,d.Entries.Count);d.Clear();Assert.Empty(d.Entries);}
    [Fact] public void PortOccupancyIsTransportErrorNotBadFrame(){var d=new CommunicationDiagnostics();d.Error(new UnauthorizedAccessException("COM5 access denied"));Assert.Equal(1,d.TransportErrors);Assert.Equal(0,d.BadFrames);}
    [Fact] public void ClosedPortIsTransportErrorNotBadFrame(){var d=new CommunicationDiagnostics();d.Error(new InvalidOperationException("The port is closed."));Assert.Equal(1,d.TransportErrors);Assert.Equal(0,d.BadFrames);}
    [Fact] public async Task RuntimeTareUsesMailboxFc16AndReadsBusinessResult(){var transport=new CommandTransport();var service=new InstrumentMonitoringService(new QueueFactory(transport));await service.ConnectAsync(Options());await service.StartMonitoringAsync();await Task.Delay(80);var runtime=new RuntimeCommandService(service);var result=await runtime.ExecuteAsync(RuntimeOperation.Tare);Assert.True(result.State==CommandExecutionState.Succeeded,result.Message);Assert.Equal((ushort)0,result.ResultCode);Assert.True(result.StateReadbackCompleted);Assert.Contains((byte)16,transport.Functions);Assert.DoesNotContain((byte)6,transport.Functions);Assert.Single(runtime.Audit);await service.DisconnectAsync();}
    [Fact] public async Task RuntimeCommandsRejectStaleSnapshotAndConcurrentClick(){var transport=new CommandTransport();var service=new InstrumentMonitoringService(new QueueFactory(transport));await service.ConnectAsync(Options());var runtime=new RuntimeCommandService(service);await Assert.ThrowsAsync<InvalidOperationException>(()=>runtime.ExecuteAsync(RuntimeOperation.Zero));await service.StartMonitoringAsync();await Task.Delay(50);transport.DelayMs=50;var first=runtime.ExecuteAsync(RuntimeOperation.Tare);await Assert.ThrowsAsync<InvalidOperationException>(()=>runtime.ExecuteAsync(RuntimeOperation.ClearTare));await first;await service.DisconnectAsync();}
    [Fact] public void DecoderUsesExactInt64Micrograms(){var values=MockTransport.RealtimeRegisters();var snapshot=InstrumentRegisterDecoder.DecodeRealtime(0,values,WordOrder.HighWordFirst);Assert.Equal(123_000_000L,snapshot.NetMassUg);Assert.Equal(123_000_000L,snapshot.DisplayMassUg);Assert.True(snapshot.Stable);Assert.Equal("123.000",MassFormatter.Format(snapshot.DisplayMassUg,1,3));}
    [Fact] public void DecoderReadsFirmwareStatusFlagsLowWordFirst(){var values=MockTransport.RealtimeRegisters();values[4]=0x0070;values[5]=0;var snapshot=InstrumentRegisterDecoder.DecodeRealtime(0,values,WordOrder.HighWordFirst);Assert.True(snapshot.Stable);Assert.True(snapshot.Zero);Assert.True(snapshot.TareActive);Assert.False(snapshot.Overload);}
    [Fact] public async Task TcpTransportHandlesSplitAndBufferedResponses(){var listener=new TcpListener(IPAddress.Loopback,0);listener.Start();var port=((IPEndPoint)listener.LocalEndpoint).Port;var server=Task.Run(async()=>{using var socket=await listener.AcceptTcpClientAsync();var stream=socket.GetStream();var request1=new byte[12];await ReadExactlyAsync(stream,request1);var response1=ModbusTcpCodec.Encode(1,1,new byte[]{3,2,1,4});var response2=ModbusTcpCodec.Encode(2,1,new byte[]{3,2,1,4});await stream.WriteAsync(response1.AsMemory(0,3));await Task.Delay(5);await stream.WriteAsync(response1.AsMemory(3));await stream.WriteAsync(response2);var request2=new byte[12];await ReadExactlyAsync(stream,request2);});await using var transport=new ModbusTcpTransport("127.0.0.1",port);await transport.OpenAsync(default);var first=await transport.ExchangeAsync(1,ModbusRequestCodec.ReadHoldingPdu(14,1),default);var second=await transport.ExchangeAsync(1,ModbusRequestCodec.ReadHoldingPdu(14,1),default);Assert.Equal((ushort)0x0104,ModbusResponseCodec.ReadHolding(first.Pdu.Span)[0]);Assert.Equal((ushort)0x0104,ModbusResponseCodec.ReadHolding(second.Pdu.Span)[0]);await server;listener.Stop();}
    [Fact] public async Task RtuTransportHandlesFragmentedResponse(){var response=Convert.FromHexString("0103020104B817");await using var stream=new FragmentedDuplexStream(response,1);await using var transport=new ModbusRtuTransport(stream);var exchange=await transport.ExchangeAsync(1,ModbusRequestCodec.ReadHoldingPdu(14,1),default);Assert.Equal((ushort)0x0104,ModbusResponseCodec.ReadHolding(exchange.Pdu.Span)[0]);Assert.Equal("0103000E0001E5C9",Convert.ToHexString(stream.Written.ToArray()));}
    [Fact] public async Task CancelledConnectReturnsDisconnected(){var transport=MockTransport.Healthy(openDelayMs:500);await using var service=new InstrumentMonitoringService(new QueueFactory(transport));using var cancellation=new CancellationTokenSource(20);await Assert.ThrowsAnyAsync<OperationCanceledException>(()=>service.ConnectAsync(Options(),cancellation.Token));Assert.Equal(MonitoringConnectionState.Disconnected,service.State);}

    private static MonitoringOptions Options()=>new(TransportMode.Tcp,PollIntervalMs:100,RequestTimeoutMs:100);
    private static ushort Address(ReadOnlyMemory<byte> pdu)=>(ushort)(pdu.Span[1]<<8|pdu.Span[2]);
    private static async Task WaitForAsync(Func<bool> condition,TimeSpan timeout){var stop=DateTime.UtcNow+timeout;while(!condition()&&DateTime.UtcNow<stop)await Task.Delay(20);Assert.True(condition());}
    private static async Task ReadExactlyAsync(Stream stream,Memory<byte> buffer){var offset=0;while(offset<buffer.Length){var count=await stream.ReadAsync(buffer[offset..]);if(count==0)throw new EndOfStreamException();offset+=count;}}

    private sealed class QueueFactory(params IModbusTransport[] transports):IModbusTransportFactory
    {private readonly Queue<IModbusTransport> queue=new(transports);public int CreateCount{get;private set;}public IModbusTransport Create(MonitoringOptions options){CreateCount++;return queue.Dequeue();}}

    private sealed class MockTransport:IModbusTransport
    {
        private readonly ushort mapVersion;private readonly int delayMs;private readonly int openDelayMs;private readonly Exception? openError;private int concurrent;
        private MockTransport(ushort mapVersion=0x0104,int delayMs=0,int openDelayMs=0,Exception? openError=null){this.mapVersion=mapVersion;this.delayMs=delayMs;this.openDelayMs=openDelayMs;this.openError=openError;}
        public static MockTransport Healthy(ushort mapVersion=0x0104,int delayMs=0,int openDelayMs=0)=>new(mapVersion,delayMs,openDelayMs);public static MockTransport OpenFailure()=>new(openError:new IOException("open failed"));
        public bool IsOpen{get;private set;}public string Endpoint=>"mock";public List<ReadOnlyMemory<byte>> Requests{get;}=[];public int MaxConcurrent{get;private set;}public Action<ReadOnlyMemory<byte>>? BeforeResponse{get;set;}
        public async Task OpenAsync(CancellationToken token){token.ThrowIfCancellationRequested();if(openError is not null)throw openError;if(openDelayMs>0)await Task.Delay(openDelayMs,token);IsOpen=true;}public Task CloseAsync(){IsOpen=false;return Task.CompletedTask;}public ValueTask DisposeAsync(){IsOpen=false;return ValueTask.CompletedTask;}
        public async Task<ModbusExchangeResult> ExchangeAsync(byte unitId,ReadOnlyMemory<byte> pdu,CancellationToken token){var active=Interlocked.Increment(ref concurrent);MaxConcurrent=Math.Max(MaxConcurrent,active);try{Requests.Add(pdu.ToArray());BeforeResponse?.Invoke(pdu);if(delayMs>0)await Task.Delay(delayMs,token);var address=Address(pdu);var count=(ushort)(pdu.Span[3]<<8|pdu.Span[4]);var registers=address switch{14=>new ushort[]{mapVersion},259=>new ushort[]{0},0=>RealtimeRegisters(),_=>new ushort[count]};if(registers.Length!=count)registers=registers.Take(count).Concat(Enumerable.Repeat((ushort)0,Math.Max(0,count-registers.Length))).ToArray();var response=new byte[2+registers.Length*2];response[0]=3;response[1]=(byte)(registers.Length*2);for(var i=0;i<registers.Length;i++){response[2+i*2]=(byte)(registers[i]>>8);response[3+i*2]=(byte)registers[i];}return new ModbusExchangeResult(response,pdu.ToArray(),response);}finally{Interlocked.Decrement(ref concurrent);}}
        public static ushort[] RealtimeRegisters(){var r=new ushort[34];r[2]=3;r[3]=1;r[4]=0x001f;Write32(r,0,123000);Write64(r,16,123_000_000);Write64(r,20,123_000_000);Write64(r,24,0);Write32(r,28,-100);Write32(r,30,-90);Write32(r,32,42);return r;}
        private static void Write32(ushort[] target,int offset,int value){target[offset]=(ushort)((uint)value>>16);target[offset+1]=(ushort)value;}private static void Write64(ushort[] target,int offset,long value){var words=RegisterValueCodec.FromInt64(value);Array.Copy(words,0,target,offset,4);}
    }

    private sealed class CommandTransport:IModbusTransport
    {public bool IsOpen{get;private set;}public string Endpoint=>"mock-command";public List<byte> Functions{get;}=[];public int DelayMs;private ushort token;private ushort command;public Task OpenAsync(CancellationToken t){IsOpen=true;return Task.CompletedTask;}public Task CloseAsync(){IsOpen=false;return Task.CompletedTask;}public ValueTask DisposeAsync()=>ValueTask.CompletedTask;public async Task<ModbusExchangeResult> ExchangeAsync(byte unit,ReadOnlyMemory<byte> pdu,CancellationToken t){Functions.Add(pdu.Span[0]);if(DelayMs>0)await Task.Delay(DelayMs,t);if(pdu.Span[0]==16){command=(ushort)(pdu.Span[8]<<8|pdu.Span[9]);token=(ushort)(pdu.Span[6]<<8|pdu.Span[7]);var echo=new byte[]{16,pdu.Span[1],pdu.Span[2],pdu.Span[3],pdu.Span[4]};return new ModbusExchangeResult(echo,pdu.ToArray(),echo);}var address=(ushort)(pdu.Span[1]<<8|pdu.Span[2]);var count=(ushort)(pdu.Span[3]<<8|pdu.Span[4]);var values=address switch{14=>new ushort[]{0x0104},259=>new ushort[]{0},76=>new ushort[]{token,0,0,command,0,0,0,0,0,0,0x0070,0},0=>MockTransport.RealtimeRegisters(),_=>new ushort[count]};if(values.Length!=count)values=values.Take(count).Concat(Enumerable.Repeat((ushort)0,Math.Max(0,count-values.Length))).ToArray();var response=new byte[2+values.Length*2];response[0]=3;response[1]=(byte)(values.Length*2);for(var i=0;i<values.Length;i++){response[2+i*2]=(byte)(values[i]>>8);response[3+i*2]=(byte)values[i];}return new ModbusExchangeResult(response,pdu.ToArray(),response);}}

    private sealed class FragmentedDuplexStream(byte[] response,int chunkSize):Stream
    {private int offset;public List<byte> Written{get;}=[];public override bool CanRead=>true;public override bool CanSeek=>false;public override bool CanWrite=>true;public override long Length=>response.Length;public override long Position{get=>offset;set=>throw new NotSupportedException();}public override void Flush(){}public override Task FlushAsync(CancellationToken token)=>Task.CompletedTask;public override int Read(byte[] buffer,int destinationOffset,int count){var take=Math.Min(Math.Min(count,chunkSize),response.Length-offset);if(take<=0)return 0;Array.Copy(response,offset,buffer,destinationOffset,take);offset+=take;return take;}public override ValueTask<int> ReadAsync(Memory<byte> buffer,CancellationToken token=default){token.ThrowIfCancellationRequested();var take=Math.Min(Math.Min(buffer.Length,chunkSize),response.Length-offset);if(take<=0)return ValueTask.FromResult(0);response.AsMemory(offset,take).CopyTo(buffer);offset+=take;return ValueTask.FromResult(take);}public override void Write(byte[] buffer,int sourceOffset,int count){Written.AddRange(buffer.AsSpan(sourceOffset,count).ToArray());}public override ValueTask WriteAsync(ReadOnlyMemory<byte> buffer,CancellationToken token=default){token.ThrowIfCancellationRequested();Written.AddRange(buffer.ToArray());return ValueTask.CompletedTask;}public override long Seek(long offset,SeekOrigin origin)=>throw new NotSupportedException();public override void SetLength(long value)=>throw new NotSupportedException();}
}
