using A33.Instrument.Protocol;
using System.Text.Json;
using Xunit;
namespace A33.Instrument.Protocol.Tests;
public class ProtocolTests {
 [Fact] public void CrcReference(){Assert.Equal((ushort)0x0bc4,ModbusCrc16.Compute(new byte[]{1,3,0,0,0,2}));}
 [Fact] public void Fc03RequestAndResponse(){var r=ModbusRequestCodec.ReadHolding(1,0,2);Assert.Equal(new byte[]{1,3,0,0,0,2},r);Assert.Equal(new ushort[]{0x0104},ModbusResponseCodec.ReadHolding(new byte[]{3,2,1,4}));}
 [Fact] public void Fc06AndFc16(){Assert.Equal(new byte[]{1,6,0,14,0xa5,0x5a},ModbusRequestCodec.WriteSingle(1,14,0xa55a));var m=ModbusRequestCodec.WriteMultiple(1,0x10,new ushort[]{0x0104,0});Assert.Equal((byte)16,m[1]);Assert.Equal((ushort)2,ModbusResponseCodec.ValidateWriteMultiple(new byte[]{16,0,16,0,0,2}));}
 [Theory][InlineData(1)][InlineData(2)][InlineData(3)][InlineData(4)][InlineData(6)] public void ExceptionCodes(byte code){var e=ModbusResponseCodec.Exception(new byte[]{0x83,code});Assert.True(e.HasValue);Assert.Equal(code,e.Value.Code);}
 [Fact] public void TcpMbapAndValidation(){var pdu=ModbusRequestCodec.ReadHolding(1,14,1);var adu=ModbusTcpCodec.Encode(1,1,pdu.AsSpan(1));Assert.Equal("0001000000060103000e0001",Convert.ToHexString(adu).ToLowerInvariant());var decoded=ModbusTcpCodec.Decode(adu,1);Assert.Equal((byte)1,decoded.Unit);Assert.Throws<ModbusFrameException>(()=>ModbusTcpCodec.Decode(adu,2));var bad=adu.ToArray();bad[2]=1;Assert.Throws<ModbusFrameException>(()=>ModbusTcpCodec.Decode(bad,1));}
 [Fact] public void TcpRejectsTidPidLengthAndUnit(){var frame=ModbusTcpCodec.Encode(7,1,ModbusRequestCodec.ReadHoldingPdu(14,1));Assert.Equal(ModbusFrameError.TransactionId,Assert.Throws<ModbusFrameException>(()=>ModbusTcpCodec.Decode(frame,8,1)).Error);var pid=frame.ToArray();pid[3]=1;Assert.Equal(ModbusFrameError.ProtocolId,Assert.Throws<ModbusFrameException>(()=>ModbusTcpCodec.Decode(pid,7,1)).Error);var length=frame.ToArray();length[5]++;Assert.Equal(ModbusFrameError.Length,Assert.Throws<ModbusFrameException>(()=>ModbusTcpCodec.Decode(length,7,1)).Error);Assert.Equal(ModbusFrameError.UnitId,Assert.Throws<ModbusFrameException>(()=>ModbusTcpCodec.Decode(frame,7,2)).Error);}
 [Fact] public void RtuFc03GoldenAndNormalResponse(){Assert.Equal("010300000002C40B",Convert.ToHexString(ModbusRtuCodec.Encode(1,ModbusRequestCodec.ReadHoldingPdu(0,2))));var response=Convert.FromHexString("01030400000000FA33");var pdu=ModbusRtuCodec.Decode(response,1,3);Assert.Equal(new ushort[]{0,0},ModbusResponseCodec.ReadHolding(pdu.Span));}
 [Fact] public void RtuRejectsCrcAddressFunctionAndLength(){var valid=Convert.FromHexString("01030400000000FA33");var crc=valid.ToArray();crc[^1]^=1;Assert.Equal(ModbusFrameError.Crc,Assert.Throws<ModbusFrameException>(()=>ModbusRtuCodec.Decode(crc,1,3)).Error);Assert.Equal(ModbusFrameError.UnitId,Assert.Throws<ModbusFrameException>(()=>ModbusRtuCodec.Decode(valid,2,3)).Error);Assert.Equal(ModbusFrameError.Function,Assert.Throws<ModbusFrameException>(()=>ModbusRtuCodec.Decode(valid,1,4)).Error);Assert.Equal(ModbusFrameError.Length,Assert.Throws<ModbusFrameException>(()=>ModbusRtuCodec.Decode(valid[..4],1,3)).Error);}
 [Fact] public void RtuAndPduExceptionsPreserveCode(){var body=new byte[]{1,0x83,6,0,0};ModbusCrc16.Append(body);var exception=Assert.Throws<ModbusExceptionResponse>(()=>ModbusRtuCodec.Decode(body,1,3));Assert.Equal((byte)6,exception.ExceptionCode);var pduException=Assert.Throws<ModbusExceptionResponse>(()=>ModbusResponseCodec.ReadHolding(new byte[]{0x83,2}));Assert.Equal((byte)2,pduException.ExceptionCode);}
 [Fact] public void Fc03RejectsFunctionByteCountAndLength(){Assert.Equal(ModbusFrameError.Function,Assert.Throws<ModbusFrameException>(()=>ModbusResponseCodec.ReadHolding(new byte[]{4,2,0,1})).Error);Assert.Equal(ModbusFrameError.ByteCount,Assert.Throws<ModbusFrameException>(()=>ModbusResponseCodec.ReadHolding(new byte[]{3,3,0,1,0})).Error);Assert.Equal(ModbusFrameError.Length,Assert.Throws<ModbusFrameException>(()=>ModbusResponseCodec.ReadHolding(new byte[]{3,4,0,1})).Error);}
 [Fact] public void SignedInt16Int32AndInt64AndWordOrder(){Assert.Equal((short)-1,RegisterValueCodec.Int16(0xffff));Assert.Equal(-1,RegisterValueCodec.Int32(new ushort[]{0xffff,0xffff}));Assert.Equal(-1,RegisterValueCodec.Int64(new ushort[]{0xffff,0xffff,0xffff,0xffff}));Assert.Equal(0x0002000100040003,RegisterValueCodec.Int64(new ushort[]{3,4,1,2},WordOrder.LowWordFirst));}
 [Fact] public void RegisterMapVersionAndNoOverlap(){Assert.Equal((ushort)0x0104,RegisterMap.Version);var used=new HashSet<int>();foreach(var d in RegisterMap.Definitions)for(var i=0;i<d.RegisterCount;i++)Assert.True(used.Add(d.Address+i),$"overlap {d.Name}");Assert.True(RegisterMap.Get("net_mass_ug").IsReadOnly);var dir=new DirectoryInfo(AppContext.BaseDirectory);while(dir is not null&&!File.Exists(Path.Combine(dir.FullName,"contracts","modbus-v0104","register-map.json")))dir=dir.Parent;Assert.NotNull(dir);using var json=JsonDocument.Parse(File.ReadAllText(Path.Combine(dir!.FullName,"contracts","modbus-v0104","register-map.json")));Assert.Equal(json.RootElement.GetArrayLength(),RegisterMap.Definitions.Count);}
}
