#ifndef MODBUS_REGISTER_TYPES_H
#define MODBUS_REGISTER_TYPES_H

typedef enum
{
    MODBUS_REGISTER_OK = 0,
    MODBUS_REGISTER_ILLEGAL_ADDRESS,
    MODBUS_REGISTER_ILLEGAL_VALUE,
    MODBUS_REGISTER_READ_ONLY,
    MODBUS_REGISTER_BUSY,
    MODBUS_REGISTER_DEVICE_FAILURE
} ModbusRegisterResult;

#endif
