#ifndef MODBUS_REGISTER_MAP_H
#define MODBUS_REGISTER_MAP_H

#define MODBUS_REGISTER_MAP_VERSION 0x0100U
#define MODBUS_REALTIME_FIRST 0x0000U
#define MODBUS_REALTIME_LAST 0x001FU
#define MODBUS_DIAGNOSTIC_FIRST 0x0020U
#define MODBUS_DIAGNOSTIC_LAST 0x003FU
#define MODBUS_MAILBOX_FIRST 0x0040U
#define MODBUS_MAILBOX_LAST 0x005FU
#define MODBUS_ACTIVE_CONFIG_FIRST 0x0100U
#define MODBUS_ACTIVE_CONFIG_LAST 0x013FU
#define MODBUS_STAGING_CONFIG_FIRST 0x0140U
#define MODBUS_STAGING_CONFIG_LAST 0x017FU
#define MODBUS_CALIBRATION_FIRST 0x0180U
#define MODBUS_CALIBRATION_LAST 0x019FU
#define MODBUS_COMMUNICATION_FIRST 0x01A0U
#define MODBUS_COMMUNICATION_LAST 0x01BFU
#define MODBUS_STORAGE_FIRST 0x01C0U
#define MODBUS_STORAGE_LAST 0x01DFU
#define MODBUS_EXECUTE_VALUE 0xA55AU

#endif
