using System.ComponentModel;
using System.IO.Ports;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Threading;
using A33.Instrument.Core;

namespace A33.Instrument.Wpf;

public sealed class MainViewModel : INotifyPropertyChanged, IAsyncDisposable
{
    private readonly InstrumentMonitoringService service=new();private readonly DispatcherTimer timer;private int transportIndex;private string host="192.168.1.100";private int port=502;private string serialPort="";private int baudRate=115200;private int unitId=1;private int connectTimeoutMs=3000;private int requestTimeoutMs=1000;private int pollIntervalMs=200;private int parityIndex;private int stopBitsIndex;
    public MainViewModel(){service.Updated+=ServiceUpdated;timer=new DispatcherTimer(TimeSpan.FromMilliseconds(250),DispatcherPriority.Background,(_,_)=>Refresh(),Dispatcher.CurrentDispatcher);ConnectCommand=Command(ConnectAsync,()=>CanConfigure);DisconnectCommand=Command(service.DisconnectAsync,()=>State!=MonitoringConnectionState.Disconnected);StartCommand=Command(()=>service.StartMonitoringAsync(),()=>State==MonitoringConnectionState.Connected);StopCommand=Command(service.StopMonitoringAsync,()=>State is MonitoringConnectionState.Monitoring or MonitoringConnectionState.Degraded or MonitoringConnectionState.Reconnecting);RefreshPortsCommand=Command(()=>{RefreshPorts();return Task.CompletedTask;});CopyDiagnosticsCommand=Command(()=>{Clipboard.SetText(service.Diagnostics.Summary());return Task.CompletedTask;});ClearDiagnosticsCommand=Command(()=>{service.Diagnostics.Clear();Refresh();return Task.CompletedTask;});RefreshPorts();Refresh();}
    public event PropertyChangedEventHandler? PropertyChanged;
    public string[] TransportModes{get;}=["Modbus TCP","Modbus RTU"];
    public int TransportIndex{get=>transportIndex;set{if(Set(ref transportIndex,value)){OnPropertyChanged(nameof(IsTcp));OnPropertyChanged(nameof(IsRtu));}}}public bool IsTcp=>TransportIndex==0;public bool IsRtu=>!IsTcp;
    public string Host{get=>host;set=>Set(ref host,value);}public int Port{get=>port;set=>Set(ref port,value);}public string SerialPort{get=>serialPort;set=>Set(ref serialPort,value);}public int BaudRate{get=>baudRate;set=>Set(ref baudRate,value);}public int UnitId{get=>unitId;set=>Set(ref unitId,value);}public int ConnectTimeoutMs{get=>connectTimeoutMs;set=>Set(ref connectTimeoutMs,value);}public int RequestTimeoutMs{get=>requestTimeoutMs;set=>Set(ref requestTimeoutMs,value);}public int PollIntervalMs{get=>pollIntervalMs;set=>Set(ref pollIntervalMs,value);}public int ParityIndex{get=>parityIndex;set=>Set(ref parityIndex,value);}public int StopBitsIndex{get=>stopBitsIndex;set=>Set(ref stopBitsIndex,value);}
    public string[] SerialPorts{get;private set;}=[];public MonitoringConnectionState State=>service.State;public bool CanConfigure=>State is MonitoringConnectionState.Disconnected or MonitoringConnectionState.Faulted;public string Endpoint=>service.Endpoint;public string MapVersion=>service.MapVersion==0?"-":$"0x{service.MapVersion:X4}";public string LastError=>service.Diagnostics.LastError;
    public string Weight=>service.Snapshot is null?"--":service.IsStale?"--":MassFormatter.Format(service.Snapshot.DisplayMassUg,service.Snapshot.Unit,service.Snapshot.DecimalPlaces);public string Unit=>service.Snapshot is null?"":MassFormatter.UnitName(service.Snapshot.Unit);public string Net=>Format(service.Snapshot?.NetMassUg);public string Gross=>Format(service.Snapshot?.GrossMassUg);public string Tare=>Format(service.Snapshot?.TareMassUg);public string Stability=>service.Snapshot is null?"--":service.Snapshot.Stable?"STABLE":"UNSTABLE";public string Zero=>service.Snapshot is null?"--":service.Snapshot.Zero?"YES":"NO";public string Overload=>service.Snapshot is null?"--":service.Snapshot.Overload?"OVERLOAD":"NORMAL";public string Checkweigh=>service.Snapshot is null?"--":new[]{"Disabled","Low","OK","High","Overload","Fault"}.ElementAtOrDefault(service.Snapshot.CheckweighState)??"Unknown";public string LastUpdate=>service.Snapshot?.CapturedAt.ToLocalTime().ToString("HH:mm:ss.fff")??"-";public string DataAge=>service.Snapshot is null?"-":$"{Math.Max(0,(DateTimeOffset.Now-service.Snapshot.CapturedAt).TotalMilliseconds):F0} ms";public bool IsStale=>service.Snapshot is not null&&service.IsStale;
    public long Tx=>service.Diagnostics.TxRequests;public long Rx=>service.Diagnostics.RxResponses;public string TxRx=>$"{Tx} / {Rx}";public long Timeouts=>service.Diagnostics.Timeouts;public long CrcErrors=>service.Diagnostics.CrcErrors;public long MbapErrors=>service.Diagnostics.MbapErrors;public long UnitErrors=>service.Diagnostics.UnitErrors;public long Exceptions=>service.Diagnostics.Exceptions;public long BadFrames=>service.Diagnostics.BadFrames;public long TransportErrors=>service.Diagnostics.TransportErrors;public long Reconnects=>service.Diagnostics.Reconnects;public string LastSuccess=>service.Diagnostics.LastSuccessAt?.ToLocalTime().ToString("HH:mm:ss.fff")??"-";public string LastRequest=>service.Diagnostics.LastRequestHex;public string LastResponse=>service.Diagnostics.LastResponseHex;
    public AsyncRelayCommand ConnectCommand{get;}public AsyncRelayCommand DisconnectCommand{get;}public AsyncRelayCommand StartCommand{get;}public AsyncRelayCommand StopCommand{get;}public AsyncRelayCommand RefreshPortsCommand{get;}public AsyncRelayCommand CopyDiagnosticsCommand{get;}public AsyncRelayCommand ClearDiagnosticsCommand{get;}
    private AsyncRelayCommand Command(Func<Task> execute,Func<bool>? canExecute=null)=>new(execute,canExecute,error=>{service.Diagnostics.Error(error);Refresh();});
    private async Task ConnectAsync(){try{var parity=ParityIndex switch{1=>Parity.Even,2=>Parity.Odd,_=>Parity.None};var stopBits=StopBitsIndex==1?StopBits.Two:StopBits.One;var options=new MonitoringOptions(IsTcp?TransportMode.Tcp:TransportMode.Rtu,Host,Port,SerialPort,BaudRate,(byte)UnitId,ConnectTimeoutMs,RequestTimeoutMs,PollIntervalMs,8,parity,stopBits);await service.ConnectAsync(options);}catch{}Refresh();}
    private string Format(long? value)=>value.HasValue&&service.Snapshot is not null?MassFormatter.Format(value.Value,service.Snapshot.Unit,service.Snapshot.DecimalPlaces):"--";
    private void RefreshPorts(){SerialPorts=System.IO.Ports.SerialPort.GetPortNames().Order().ToArray();if(string.IsNullOrEmpty(SerialPort)&&SerialPorts.Length>0)SerialPort=SerialPorts[0];OnPropertyChanged(nameof(SerialPorts));}
    private void ServiceUpdated(object? sender,EventArgs e)=>Application.Current.Dispatcher.BeginInvoke(Refresh);
    private void Refresh(){foreach(var name in new[]{nameof(State),nameof(CanConfigure),nameof(Endpoint),nameof(MapVersion),nameof(LastError),nameof(Weight),nameof(Unit),nameof(Net),nameof(Gross),nameof(Tare),nameof(Stability),nameof(Zero),nameof(Overload),nameof(Checkweigh),nameof(LastUpdate),nameof(DataAge),nameof(IsStale),nameof(Tx),nameof(Rx),nameof(TxRx),nameof(Timeouts),nameof(CrcErrors),nameof(MbapErrors),nameof(UnitErrors),nameof(Exceptions),nameof(BadFrames),nameof(TransportErrors),nameof(Reconnects),nameof(LastSuccess),nameof(LastRequest),nameof(LastResponse)})OnPropertyChanged(name);foreach(var command in new[]{ConnectCommand,DisconnectCommand,StartCommand,StopCommand})command.RaiseCanExecuteChanged();}
    private bool Set<T>(ref T field,T value,[CallerMemberName]string? name=null){if(EqualityComparer<T>.Default.Equals(field,value))return false;field=value;OnPropertyChanged(name);return true;}private void OnPropertyChanged([CallerMemberName]string? name=null)=>PropertyChanged?.Invoke(this,new PropertyChangedEventArgs(name));
    public async ValueTask DisposeAsync(){timer.Stop();service.Updated-=ServiceUpdated;await service.DisposeAsync();}
}
